#!/bin/sh -u
PATH=/bin:/usr/bin:/sbin:/usr/sbin ; export PATH          # (2) PATH line
umask 022                                 # (3) umask line

# This script generates the system information summary as the output.
# The summary includes the current date and time, name of the account
# the script is running as, the number of CPU cores, total amount of
# RAM in GB, the running time of the system, pathnames of hard drives,
# info of swap areas, disk usage, device files and something fun.

echo
echo
echo "System Summary"
echo "=============="
echo
echo "Generated on:           `date`"
echo "Generated by:           `whoami`"
echo "Number of CPU cores:    `nproc`"
echo "RAM:                    $(free -h | awk '/Mem:/ { print $2 } ')"
echo "System running time:    `uptime -p`"
echo 
echo
echo "Hard Drive Files"
echo "----------------"
echo "`find /dev -name "sd*"`"
echo
echo
echo "Swap Areas"
echo "----------"
echo "`swapon`"
echo 
echo
echo "Disk Usage"
echo "----------"
echo "`df -h`"
echo
echo
echo "Device Files"
echo "------------"
echo "`mount | grep "^/dev"`"
echo
echo
echo "Fun Loops"
echo "---------"

for n in tiger monkey lion ; do
    echo "The zoo has a $n!"
done

echo
echo
